# Generated by Django 3.2.19 on 2023-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_player_employ_dwarf_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='employ_dwarf_salary',
            field=models.FloatField(default=0.2),
        ),
    ]
